using quest_web_dotnet.Models;

namespace quest_web_dotnet.Seeds
{
    public class SeedPosts
    {
        public List<Post> getFakePosts(int userId)
        {
            return new List<Post>
            {
                new Post()
                {
                    UserId = userId,
                    Title = "Zelda Tears of the Kingdom : de jolis cadeaux pour les abonnés",
                    Content = "\r\n\r\n# Nintendo a encore une poignée de cadeaux pour les fans de The Legend of Zelda Tears of the Kingdom. \n\nIl faudra néanmoins être abonné au Nintendo Switch Online pour en profiter.\r\n\r\nZelda Tears of the Kingdom est un véritable raz-de-marée. Succès critique et commercial, la dernière exclusivité Nintendo Switch atomise tous les records avec ses 10 millions de ventes dans le monde entier en trois jours seulement. Un démarrage historique qui matérialise l’engouement démesuré des joueurs depuis ces derniers mois. Et si vous êtes conquis par le dernier épisode de cette saga légendaire, Big N a de jolis cadeaux pour vous… à condition que vous soyez abonnés au Nintendo Switch Online.\r\nDe nouveaux avatars Zelda Tears of the Kingdom\r\n\r\nPresque deux semaines après sa sortie, Zelda Tears of the Kingdom est encore sur toutes les lèvres. Certains partagent leurs créations les plus folles, la communauté s’entraide, les vidéos démentes pullulent sur les réseaux sociaux… bref le phénomène n’est pas prêt de s’arrêter. On se doute que Nintendo a déjà prévu de surfer sur le succès. Le site officiel du jeu avait plus ou moins vendu la mèche, au moins un DLC serait prévu. Big N attendra sans doute que le soufflé retombe pour le dévoiler, il faudra donc prendre son mal en patience. En attendant, les fans de Zelda TOTK abonnés au Nintendo Switch Online peuvent mettre la main sur de nouveaux avatars. \r\n\r\nLa seconde et dernière vague d'icônes de Zelda Tears of the Kingdom comprend donc des avatars à l’effigie de Link, Sidon, Ganondorf, Riju ou encore Babil, mais aussi de la célèbre Master Sword. Comme d’habitude, quelques cadres et fonds peuvent être récupérés moyennant une poignée de points platine. Comptez 150 points pour mettre la main sur tout. Ces avatars Nintendo Switch Online de The Legend of Zelda TOTK seront disponibles jusqu’au 26 mai 2023 à 2h59, heure française. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Alien : la franchise culte de retour mais ça risque de décevoir",
                    Content = "\r\n\r\nCela fait des années que les fans attendent un retour digne de ce nom de la franchise Alien. Et visiblement Disney serait en train de préparer quelque chose.\r\n\r\nSi vous aimez la saga Alien, depuis Alien : Covenant en 2017 il n'y pas grand chose à se mettre sous la dent. D'autant plus si vous attendez quelque chose du coté de versus Predator, la rencontre très conflictuelle entre les deux races extraterrestres qui n'ont qu'une seule envie : s'entretuer. Malgré tout le géant Disney semble avoir entre les mains un projet sur la franchise. À quoi s'attendre ?\r\nDisney et Alien, un projet improbable\r\n\r\nSi vous êtes fan d'Alien vs Predator, accrochez vous bien car Disney aurait dans les cartons un projet de série d'animation AvP. C'est lors d’un épisode du podcast Perfect Organism le mois dernier que Joshua Izzo, créateur de l’Alien Day a partagé quelques détails à propos de cet anime. Plus précisément on peut même apprendre que la série est déjà terminée coté réalisation et qu'il ne manque plus qu'un feu vert.\r\n\r\nL'homme déclare ainsi :\r\n\r\n    Chez 20th Century Studios, enfin chez Disney maintenant, il y a un anime Alien vs. Predator que j’ai produit. La série est finie et elle dure 10 épisodes.\r\n"
                },
                new Post()
                {
                    UserId = userId,
                    Title = " Gran Turismo 7 : une nouvelle mise à jour arrive, avec de grands classiques\r\n",
                    Content = "\r\n\r\nLa mise à jour de Gran Turismo 7 de mai 2023 approche et une poignée de nouvelles voitures gratuites. Une sélection moins importante qui divise la communauté.\r\n\r\nLa fin du mois approche et la nouvelle mise à jour de Gran Turismo 7 avec. Polyphony Digital avait frappé fort pour célébrer le premier anniversaire de son jeu service. C'était pas moins de cinq nouvelles voitures, des menus inédits, des pistes flambant neuves l’arrivée du VRR (Variable Refresh Rate) et la possibilité de jouer à 120Hz sur PS5 qui avaient été déployés. Le programme sera forcément moins reluisant avec l’update de mai 2023. Les développeurs vont retourner à leur rythme habituel de trois nouveaux bolides gratuits déployés. Le teasing du créateur laisse néanmoins entrevoir le retour de classiques de la licence.\r\nTrois nouvelles voitures dans Gran Turismo 7\r\n\r\nLa nouvelle mise à jour de Gran Turismo 7 sera déployée cette semaine sur PS5 et PS4. Comme à son habitude, Kazunori Yamauchi, le créateur de la licence, a publié son petit tweet mensuel dévoilant la silhouette des nouvelles voitures gratuites qui arriveront avec le prochain patch. Polyphony Digital avait dernièrement écouté la communauté et fait plus d’ajouts de véhicules mensuels qu’à l’accoutumée. Dernièrement, les véhicules arrivaient par salves de quatre ou cinq. Retour au programme habituel cette fois. Ce sont donc trois bolides qui arriveront d’ici quelques jours dans GT7. Les ombres étant plus accentuées qu’à l’accoutumée, il est plus difficile pour la communauté de devenir à l’avance leur identité. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Zelda Tears of the Kingdom : de jolis cadeaux pour les abonnés",
                    Content = "\r\n\r\nNintendo a encore une poignée de cadeaux pour les fans de The Legend of Zelda Tears of the Kingdom. Il faudra néanmoins être abonné au Nintendo Switch Online pour en profiter.\r\n\r\nZelda Tears of the Kingdom est un véritable raz-de-marée. Succès critique et commercial, la dernière exclusivité Nintendo Switch atomise tous les records avec ses 10 millions de ventes dans le monde entier en trois jours seulement. Un démarrage historique qui matérialise l’engouement démesuré des joueurs depuis ces derniers mois. Et si vous êtes conquis par le dernier épisode de cette saga légendaire, Big N a de jolis cadeaux pour vous… à condition que vous soyez abonnés au Nintendo Switch Online.\r\nDe nouveaux avatars Zelda Tears of the Kingdom\r\n\r\nPresque deux semaines après sa sortie, Zelda Tears of the Kingdom est encore sur toutes les lèvres. Certains partagent leurs créations les plus folles, la communauté s’entraide, les vidéos démentes pullulent sur les réseaux sociaux… bref le phénomène n’est pas prêt de s’arrêter. On se doute que Nintendo a déjà prévu de surfer sur le succès. Le site officiel du jeu avait plus ou moins vendu la mèche, au moins un DLC serait prévu. Big N attendra sans doute que le soufflé retombe pour le dévoiler, il faudra donc prendre son mal en patience. En attendant, les fans de Zelda TOTK abonnés au Nintendo Switch Online peuvent mettre la main sur de nouveaux avatars. \r\n\r\nLa seconde et dernière vague d'icônes de Zelda Tears of the Kingdom comprend donc des avatars à l’effigie de Link, Sidon, Ganondorf, Riju ou encore Babil, mais aussi de la célèbre Master Sword. Comme d’habitude, quelques cadres et fonds peuvent être récupérés moyennant une poignée de points platine. Comptez 150 points pour mettre la main sur tout. Ces avatars Nintendo Switch Online de The Legend of Zelda TOTK seront disponibles jusqu’au 26 mai 2023 à 2h59, heure française. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Alien : la franchise culte de retour mais ça risque de décevoir",
                    Content = "\r\n\r\nCela fait des années que les fans attendent un retour digne de ce nom de la franchise Alien. Et visiblement Disney serait en train de préparer quelque chose.\r\n\r\nSi vous aimez la saga Alien, depuis Alien : Covenant en 2017 il n'y pas grand chose à se mettre sous la dent. D'autant plus si vous attendez quelque chose du coté de versus Predator, la rencontre très conflictuelle entre les deux races extraterrestres qui n'ont qu'une seule envie : s'entretuer. Malgré tout le géant Disney semble avoir entre les mains un projet sur la franchise. À quoi s'attendre ?\r\nDisney et Alien, un projet improbable\r\n\r\nSi vous êtes fan d'Alien vs Predator, accrochez vous bien car Disney aurait dans les cartons un projet de série d'animation AvP. C'est lors d’un épisode du podcast Perfect Organism le mois dernier que Joshua Izzo, créateur de l’Alien Day a partagé quelques détails à propos de cet anime. Plus précisément on peut même apprendre que la série est déjà terminée coté réalisation et qu'il ne manque plus qu'un feu vert.\r\n\r\nL'homme déclare ainsi :\r\n\r\n    Chez 20th Century Studios, enfin chez Disney maintenant, il y a un anime Alien vs. Predator que j’ai produit. La série est finie et elle dure 10 épisodes.\r\n"
                },
                new Post()
                {
                    UserId = userId,
                    Title = " Gran Turismo 7 : une nouvelle mise à jour arrive, avec de grands classiques\r\n",
                    Content = "\r\n\r\nLa mise à jour de Gran Turismo 7 de mai 2023 approche et une poignée de nouvelles voitures gratuites. Une sélection moins importante qui divise la communauté.\r\n\r\nLa fin du mois approche et la nouvelle mise à jour de Gran Turismo 7 avec. Polyphony Digital avait frappé fort pour célébrer le premier anniversaire de son jeu service. C'était pas moins de cinq nouvelles voitures, des menus inédits, des pistes flambant neuves l’arrivée du VRR (Variable Refresh Rate) et la possibilité de jouer à 120Hz sur PS5 qui avaient été déployés. Le programme sera forcément moins reluisant avec l’update de mai 2023. Les développeurs vont retourner à leur rythme habituel de trois nouveaux bolides gratuits déployés. Le teasing du créateur laisse néanmoins entrevoir le retour de classiques de la licence.\r\nTrois nouvelles voitures dans Gran Turismo 7\r\n\r\nLa nouvelle mise à jour de Gran Turismo 7 sera déployée cette semaine sur PS5 et PS4. Comme à son habitude, Kazunori Yamauchi, le créateur de la licence, a publié son petit tweet mensuel dévoilant la silhouette des nouvelles voitures gratuites qui arriveront avec le prochain patch. Polyphony Digital avait dernièrement écouté la communauté et fait plus d’ajouts de véhicules mensuels qu’à l’accoutumée. Dernièrement, les véhicules arrivaient par salves de quatre ou cinq. Retour au programme habituel cette fois. Ce sont donc trois bolides qui arriveront d’ici quelques jours dans GT7. Les ombres étant plus accentuées qu’à l’accoutumée, il est plus difficile pour la communauté de devenir à l’avance leur identité. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Zelda Tears of the Kingdom : de jolis cadeaux pour les abonnés",
                    Content = "\r\n\r\nNintendo a encore une poignée de cadeaux pour les fans de The Legend of Zelda Tears of the Kingdom. Il faudra néanmoins être abonné au Nintendo Switch Online pour en profiter.\r\n\r\nZelda Tears of the Kingdom est un véritable raz-de-marée. Succès critique et commercial, la dernière exclusivité Nintendo Switch atomise tous les records avec ses 10 millions de ventes dans le monde entier en trois jours seulement. Un démarrage historique qui matérialise l’engouement démesuré des joueurs depuis ces derniers mois. Et si vous êtes conquis par le dernier épisode de cette saga légendaire, Big N a de jolis cadeaux pour vous… à condition que vous soyez abonnés au Nintendo Switch Online.\r\nDe nouveaux avatars Zelda Tears of the Kingdom\r\n\r\nPresque deux semaines après sa sortie, Zelda Tears of the Kingdom est encore sur toutes les lèvres. Certains partagent leurs créations les plus folles, la communauté s’entraide, les vidéos démentes pullulent sur les réseaux sociaux… bref le phénomène n’est pas prêt de s’arrêter. On se doute que Nintendo a déjà prévu de surfer sur le succès. Le site officiel du jeu avait plus ou moins vendu la mèche, au moins un DLC serait prévu. Big N attendra sans doute que le soufflé retombe pour le dévoiler, il faudra donc prendre son mal en patience. En attendant, les fans de Zelda TOTK abonnés au Nintendo Switch Online peuvent mettre la main sur de nouveaux avatars. \r\n\r\nLa seconde et dernière vague d'icônes de Zelda Tears of the Kingdom comprend donc des avatars à l’effigie de Link, Sidon, Ganondorf, Riju ou encore Babil, mais aussi de la célèbre Master Sword. Comme d’habitude, quelques cadres et fonds peuvent être récupérés moyennant une poignée de points platine. Comptez 150 points pour mettre la main sur tout. Ces avatars Nintendo Switch Online de The Legend of Zelda TOTK seront disponibles jusqu’au 26 mai 2023 à 2h59, heure française. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Alien : la franchise culte de retour mais ça risque de décevoir",
                    Content = "\r\n\r\nCela fait des années que les fans attendent un retour digne de ce nom de la franchise Alien. Et visiblement Disney serait en train de préparer quelque chose.\r\n\r\nSi vous aimez la saga Alien, depuis Alien : Covenant en 2017 il n'y pas grand chose à se mettre sous la dent. D'autant plus si vous attendez quelque chose du coté de versus Predator, la rencontre très conflictuelle entre les deux races extraterrestres qui n'ont qu'une seule envie : s'entretuer. Malgré tout le géant Disney semble avoir entre les mains un projet sur la franchise. À quoi s'attendre ?\r\nDisney et Alien, un projet improbable\r\n\r\nSi vous êtes fan d'Alien vs Predator, accrochez vous bien car Disney aurait dans les cartons un projet de série d'animation AvP. C'est lors d’un épisode du podcast Perfect Organism le mois dernier que Joshua Izzo, créateur de l’Alien Day a partagé quelques détails à propos de cet anime. Plus précisément on peut même apprendre que la série est déjà terminée coté réalisation et qu'il ne manque plus qu'un feu vert.\r\n\r\nL'homme déclare ainsi :\r\n\r\n    Chez 20th Century Studios, enfin chez Disney maintenant, il y a un anime Alien vs. Predator que j’ai produit. La série est finie et elle dure 10 épisodes.\r\n"
                },
                new Post()
                {
                    UserId = userId,
                    Title = " Gran Turismo 7 : une nouvelle mise à jour arrive, avec de grands classiques\r\n",
                    Content = "\r\n\r\nLa mise à jour de Gran Turismo 7 de mai 2023 approche et une poignée de nouvelles voitures gratuites. Une sélection moins importante qui divise la communauté.\r\n\r\nLa fin du mois approche et la nouvelle mise à jour de Gran Turismo 7 avec. Polyphony Digital avait frappé fort pour célébrer le premier anniversaire de son jeu service. C'était pas moins de cinq nouvelles voitures, des menus inédits, des pistes flambant neuves l’arrivée du VRR (Variable Refresh Rate) et la possibilité de jouer à 120Hz sur PS5 qui avaient été déployés. Le programme sera forcément moins reluisant avec l’update de mai 2023. Les développeurs vont retourner à leur rythme habituel de trois nouveaux bolides gratuits déployés. Le teasing du créateur laisse néanmoins entrevoir le retour de classiques de la licence.\r\nTrois nouvelles voitures dans Gran Turismo 7\r\n\r\nLa nouvelle mise à jour de Gran Turismo 7 sera déployée cette semaine sur PS5 et PS4. Comme à son habitude, Kazunori Yamauchi, le créateur de la licence, a publié son petit tweet mensuel dévoilant la silhouette des nouvelles voitures gratuites qui arriveront avec le prochain patch. Polyphony Digital avait dernièrement écouté la communauté et fait plus d’ajouts de véhicules mensuels qu’à l’accoutumée. Dernièrement, les véhicules arrivaient par salves de quatre ou cinq. Retour au programme habituel cette fois. Ce sont donc trois bolides qui arriveront d’ici quelques jours dans GT7. Les ombres étant plus accentuées qu’à l’accoutumée, il est plus difficile pour la communauté de devenir à l’avance leur identité. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Zelda Tears of the Kingdom : de jolis cadeaux pour les abonnés",
                    Content = "\r\n\r\nNintendo a encore une poignée de cadeaux pour les fans de The Legend of Zelda Tears of the Kingdom. Il faudra néanmoins être abonné au Nintendo Switch Online pour en profiter.\r\n\r\nZelda Tears of the Kingdom est un véritable raz-de-marée. Succès critique et commercial, la dernière exclusivité Nintendo Switch atomise tous les records avec ses 10 millions de ventes dans le monde entier en trois jours seulement. Un démarrage historique qui matérialise l’engouement démesuré des joueurs depuis ces derniers mois. Et si vous êtes conquis par le dernier épisode de cette saga légendaire, Big N a de jolis cadeaux pour vous… à condition que vous soyez abonnés au Nintendo Switch Online.\r\nDe nouveaux avatars Zelda Tears of the Kingdom\r\n\r\nPresque deux semaines après sa sortie, Zelda Tears of the Kingdom est encore sur toutes les lèvres. Certains partagent leurs créations les plus folles, la communauté s’entraide, les vidéos démentes pullulent sur les réseaux sociaux… bref le phénomène n’est pas prêt de s’arrêter. On se doute que Nintendo a déjà prévu de surfer sur le succès. Le site officiel du jeu avait plus ou moins vendu la mèche, au moins un DLC serait prévu. Big N attendra sans doute que le soufflé retombe pour le dévoiler, il faudra donc prendre son mal en patience. En attendant, les fans de Zelda TOTK abonnés au Nintendo Switch Online peuvent mettre la main sur de nouveaux avatars. \r\n\r\nLa seconde et dernière vague d'icônes de Zelda Tears of the Kingdom comprend donc des avatars à l’effigie de Link, Sidon, Ganondorf, Riju ou encore Babil, mais aussi de la célèbre Master Sword. Comme d’habitude, quelques cadres et fonds peuvent être récupérés moyennant une poignée de points platine. Comptez 150 points pour mettre la main sur tout. Ces avatars Nintendo Switch Online de The Legend of Zelda TOTK seront disponibles jusqu’au 26 mai 2023 à 2h59, heure française. "
                },
                new Post()
                {
                    UserId = userId,
                    Title = "Alien : la franchise culte de retour mais ça risque de décevoir",
                    Content = "\r\n\r\nCela fait des années que les fans attendent un retour digne de ce nom de la franchise Alien. Et visiblement Disney serait en train de préparer quelque chose.\r\n\r\nSi vous aimez la saga Alien, depuis Alien : Covenant en 2017 il n'y pas grand chose à se mettre sous la dent. D'autant plus si vous attendez quelque chose du coté de versus Predator, la rencontre très conflictuelle entre les deux races extraterrestres qui n'ont qu'une seule envie : s'entretuer. Malgré tout le géant Disney semble avoir entre les mains un projet sur la franchise. À quoi s'attendre ?\r\nDisney et Alien, un projet improbable\r\n\r\nSi vous êtes fan d'Alien vs Predator, accrochez vous bien car Disney aurait dans les cartons un projet de série d'animation AvP. C'est lors d’un épisode du podcast Perfect Organism le mois dernier que Joshua Izzo, créateur de l’Alien Day a partagé quelques détails à propos de cet anime. Plus précisément on peut même apprendre que la série est déjà terminée coté réalisation et qu'il ne manque plus qu'un feu vert.\r\n\r\nL'homme déclare ainsi :\r\n\r\n    Chez 20th Century Studios, enfin chez Disney maintenant, il y a un anime Alien vs. Predator que j’ai produit. La série est finie et elle dure 10 épisodes.\r\n"
                },
                new Post()
                {
                    UserId = userId,
                    Title = " Gran Turismo 7 : une nouvelle mise à jour arrive, avec de grands classiques\r\n",
                    Content = "\r\n\r\nLa mise à jour de Gran Turismo 7 de mai 2023 approche et une poignée de nouvelles voitures gratuites. Une sélection moins importante qui divise la communauté.\r\n\r\nLa fin du mois approche et la nouvelle mise à jour de Gran Turismo 7 avec. Polyphony Digital avait frappé fort pour célébrer le premier anniversaire de son jeu service. C'était pas moins de cinq nouvelles voitures, des menus inédits, des pistes flambant neuves l’arrivée du VRR (Variable Refresh Rate) et la possibilité de jouer à 120Hz sur PS5 qui avaient été déployés. Le programme sera forcément moins reluisant avec l’update de mai 2023. Les développeurs vont retourner à leur rythme habituel de trois nouveaux bolides gratuits déployés. Le teasing du créateur laisse néanmoins entrevoir le retour de classiques de la licence.\r\nTrois nouvelles voitures dans Gran Turismo 7\r\n\r\nLa nouvelle mise à jour de Gran Turismo 7 sera déployée cette semaine sur PS5 et PS4. Comme à son habitude, Kazunori Yamauchi, le créateur de la licence, a publié son petit tweet mensuel dévoilant la silhouette des nouvelles voitures gratuites qui arriveront avec le prochain patch. Polyphony Digital avait dernièrement écouté la communauté et fait plus d’ajouts de véhicules mensuels qu’à l’accoutumée. Dernièrement, les véhicules arrivaient par salves de quatre ou cinq. Retour au programme habituel cette fois. Ce sont donc trois bolides qui arriveront d’ici quelques jours dans GT7. Les ombres étant plus accentuées qu’à l’accoutumée, il est plus difficile pour la communauté de devenir à l’avance leur identité. "
                },
            };
        }
    }
}
